### ISSUE TITLE
Fail code 422

### ISSUE THREAD

**Issue by hbi99** [PatrickJongmans/push_acs_php#1]
Hi,
This code worked great until recently...now, it returns fail code 422.
The message is: Missing fields. Required: to_ids or friends

The thing is that there were no need for "to_ids" earlier. Do you know what might be wrong?

Thanks in advance

**Comment by PatrickJongmans** [comment]
Hi Hakan,

http://docs.appcelerator.com/cloud/latest/#!/api/PushNotifications-method-notify 
http://docs.appcelerator.com/cloud/latest/#%21/api/PushNotifications-method-notify 

You have to use: 'everyone' according to the 
documentation:http://docs.appcelerator.com/cloud/latest/#%21/api/PushNotifications-method-notify
- to_ids: String
  
  Comma-separated list of user IDs to send the notification to users
  who are subscribed to the specified channel. Up to 1000 users can be
  specified.
  
  Application admins can set this parameter to|everyone|to send to all
  devices subscribed to the channel.
  
  If you are using the web interface, you do not need to specify this
  parameter.

Regards,
Patrick
